name: Build and test Go
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Install golangci-lint
        run: |
          mkdir -p $HOME/bin 
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/bin v1.18.0
          echo ::add-path::$HOME/bin

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Running CI
        run: make ci
